version: "3"
services:
    web:
        image: demo:latest
        env_file: 
            - web.env
        ports:
            - "8000:80"
        volumes:
            - aspnetb4-data:/app/Logs
volumes:
     aspnetb4-data: 
        external: true